# @see https://github.com/Sylius/SyliusResourceBundle/blob/master/docs/index.md
sylius_resource:
    # Override default settings
    #settings:

    # Configure your resources
    resources:
        #app.book:
            #classes:
                #model: App\Entity\Book
